spring.application.name=financial-api

spring.datasource.url=jdbc:postgresql://172.31.192.1:5434/financial_api
spring.datasource.username=financial_api_user
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
